sumo_coders_framework_search:
    resource: "@SumoCodersFrameworkSearchBundle/Controller/"
    type:     annotation
    prefix:   /

sumo_coders_framework_core:
    resource: "@SumoCodersFrameworkCoreBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

sumo_coders_framework_multi_user:
    resource: "@SumoCodersFrameworkMultiUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
