sumo_coders_framework_search:
    resource: "@SumoCodersFrameworkSearchBundle/Controller/"
    type:     annotation
    prefix:   /

sumo_coders_framework_core:
    resource: "@SumoCodersFrameworkCoreBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

sumo_coders_framework_multi_user:
    resource: "@SumoCodersFrameworkMultiUserBundle/Resources/config/routing.yml"
    prefix:   /

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /_trans
